const menu = [
    {
      id: 1,
      title: 'Dr. Arlen Stoltenberg IV ',
      category: 'ENT - optimize B2B infomediaries',
      price: 15.99,
      img: './images/success.png',
      desc: `Dr. Arlen Stoltenberg IV is ENT specialist `,
    },
    {
      id: 2,
      title: 'Dr. Charley Lowe',
      category: 'General Doctor',
      price: 13.99,
      img: './images/success.png',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'Dr. Mackenzie Miller',
      category: 'skin',
      price: 6.99,
      img: './images/success.png',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'Dr. Leatrice Ondricka',
      category: 'General doctor',
      price: 20.99,
      img: './images/success.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'Dr. Ronald Hauck',
      category: 'Skin',
      price: 22.99,
      img: './images/success.png',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'Dr. Edyth Hayes',
      category: 'Child Care',
      price: 18.99,
      img: './images/success.png',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'Dr. Gillian Nolan',
      category: 'Mental Health',
      price: 8.99,
      img: './images/success.png',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Dr. Osvaldo Nikolaus',
      category: 'ENT',
      price: 12.99,
      img: './images/success.png',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Dr. Clement Watsica Sr.',
      category: 'Dentist',
      price: 16.99,
      img: './images/success.png',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;